name: WeaponSystem
version: 1.0
author: paulO5
main: de.paul.weaponsystem.WeaponSystem
commands:
   getWeapon:
      description: Gibt dir eine Waffe.
   getMuni:
      description: Gibt dir Muni.
   placeCrate:
      description: Platziert ein Lager.