name: WeaponSystem
version: 1.0
author: paulO5
main: de.paul.weaponsystem.WeaponSystem
depend: [Vault, RevieveNew]
commands:
   getWeapon:
      description: Gibt dir eine Waffe.
   getMuni:
      description: Gibt dir Muni.
   placeCrate:
      description: Platziert ein Lager.
   placeShopNPC:
      description: Platziert einen Shop NPC.
   placeStorage:
      description: Platziert einen Schrank.
   dealWeapon:
      description: Deale eine Waffe mit einem Spieler.